### ISSUE TITLE
polyglot_data on windows.

### ISSUE THREAD

**Issue by xTomax** [aboSamoor/polyglot#12]
Hi,
Have installed polyglot on windows with python 3.4, after some lib problems solved, I start getting this error:

downloader.download()
Polyglot Downloader
#---------------------------------------------------------------------------
  d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
#---------------------------------------------------------------------------
Downloader> l

Collections:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 649, in download
    self._interactive_download()
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 1068, in _interactive_download
    DownloaderShell(self).run()
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 1096, in run
    more_prompt=True)
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 459, in list
    for info in sorted(getattr(self, category)(), key=str):
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 495, in collections
    self._update_index()
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 832, in _update_index
    P = Package.fromcsobj(p)
  File "C:\Python34\lib\site-packages\polyglot-15.5.2-py3.4.egg\polyglot\downloader.py", line 232, in fromcsobj
    language = subdir.split(path.sep)[1]
IndexError: list index out of range

After some analysis (and some neurons less...) e got the problem, on windows "path.sep" is,as expected "\\" instead of "/", since the packages are "named" or "ID(ed)" with "/" it makes no sense the path.sep on windows users? Or am I missing something I should had installed?

A replace on path.sep for "/" solve the problem and allow me to list and download any data I want to my polyglot installation.

**Comment by aboSamoor** [comment]
Send me a pull request and I will review it :).

**Comment by xTomax** [comment]
It is done. Please check it when you got time. Thanks ;)

**Comment by GraphGrail** [comment]
@xTomax please could you tell me how you solved install problems on Win (x64)?
I have:

C:\Program Files (x86)\PowerCmd>pip install polyglot
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting polyglot

    100% |################################| 131kB 787kB/s 
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\Users\Joomler\AppData\Local\Temp\pip-build-_g_evgl3\polyglot\setup.py", line 14, in <module>
    with open('README.rst') as readme_file:
OSError: [Errno 22] Invalid argument: 'README.rst'
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Joomler\AppData\Local\Temp\pip-build-_g_evgl3\polyglot\setup.py", line 14, in <module>
        with open('README.rst') as readme_file:
    OSError: [Errno 22] Invalid argument: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "C:\Users\Joomler\AppData\Local\Temp\pip-build-_g_evgl3\polyglot\setup.py", line 14, in <module>
    
        with open('README.rst') as readme_file:
    
    OSError: [Errno 22] Invalid argument: 'README.rst'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Joomler\AppData\Local\Temp\pip-build-_g_evgl3\polyglot

**Comment by xTomax** [comment]
That was the easy one ;)
There are 2 files with the same name in polyglot/docs/ (README.rst and readme.rst) and the windows freaks out. You need to remove one of them.

**Comment by krishnateja614** [comment]
@xTomax I'm getting the same error as your first post in this thread  in Windows 64. What is the fix you did to resolve that?. I didn't quite get what you said about replacing the path.sep line argument with "/"

**Comment by xTomax** [comment]
@krishnateja614 
Open the polyglot\downloader.py file, find the "language = subdir.split(path.sep)[1]" line, and change path.sep to "/".
On a windows system path.sep will return '\' but the packages separator is '/'.

**Comment by OriStartapp** [comment]
hi 
 can you please attached the new downloader.py  file .
seems the solution doesn't work for me

**Comment by devappamazing** [comment]
@xtomax
can you please share the downloader.py
I try to do as above change path.sep to "/".
but it didn't work

**Comment by xTomax** [comment]
@devappamazing Is this what you endup with? : language = subdir.split("/")[1] ?
Are you using the correct python version?
If didn't work try to import os and change it to os.sep
If non of the above worked, post the error you are getting.

**Comment by devappamazing** [comment]
@xtomax
 thanks for the quick answer , 
 i run:
text = Text(u"In Großbritannien war Gandhi mit dem westlichen Lebensstil vertraut geworden")
print(text.entities)

the result i get (I did try to use os to ):
text = Text(u"In Großbritannien war Gandhi mit dem westlichen Lebensstil vertraut geworden")
print(text.entities)
Traceback (most recent call last):

  File "<ipython-input-33-68602f14b8f2>", line 2, in <module>
    print(text.entities)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\text.py", line 132, in entities
    for i, (w, tag) in enumerate(self.ne_chunker.annotate(self.words)):

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\text.py", line 100, in ne_chunker
    return get_ner_tagger(lang=self.language.code)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\tag\base.py", line 191, in get_ner_tagger
    return NEChunker(lang=lang)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\tag\base.py", line 104, in __init__
    super(NEChunker, self).__init__(lang=lang)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\tag\base.py", line 40, in __init__
    self.predictor = self._load_network()

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\tag\base.py", line 109, in _load_network
    self.embeddings = load_embeddings(self.lang, type='cw', normalize=True)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\load.py", line 61, in load_embeddings
    p = locate_resource(src_dir, lang)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\load.py", line 43, in locate_resource
    if downloader.status(package_id) != downloader.INSTALLED:

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\downloader.py", line 737, in status
    info = self._info_or_id(info_or_id)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\downloader.py", line 507, in _info_or_id
    return self.info(info_or_id)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\downloader.py", line 929, in info
    self._update_index() # If package is not found, most probably we did not

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\downloader.py", line 843, in _update_index
    P = Package.fromcsobj(p)

  File "C:\Users\Ori\Anaconda2\lib\site-packages\polyglot\downloader.py", line 216, in fromcsobj
    language = subdir.split("/")[1]

IndexError: list index out of range

**Comment by xTomax** [comment]
@devappamazing 
My solution solve the problem downloading / on the download part while installing.
Your problem seams a bit diferente, did you install the languages correctly? Could you use the downloader?

I'm sorry I'm no longer working with this project, and left it about a year ago, so I may not be that good of an help.

**Comment by pythonabehs** [comment]
Hi, Im facing the same issue
How can I correct this?
im running: 
text = Text(u"O primeiro uso de desobedincia civil em massa ocorreu em setembro de 1906.")
for word, tag in text.pos_tags:
    print(u"{:<16}{:>2}".format(word, tag))
error:
Traceback (most recent call last):

  File "<ipython-input-28-d4de72d62a16>", line 1, in <module>
    runfile('C:/Users/a/Anaconda3/Programs/polyglot_practise.py', wdir='C:/Users/a/Anaconda3/Programs')

  File "C:\Users\a\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\a\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/a/Anaconda3/Programs/polyglot_practise.py", line 19, in <module>
    for word, tag in text.pos_tags:

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\text.py", line 157, in pos_tags
    for word,t in self.pos_tagger.annotate(self.words):

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\text.py", line 106, in pos_tagger
    return get_pos_tagger(lang=self.language.code)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\tag\base.py", line 181, in get_pos_tagger
    return POSTagger(lang=lang)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\tag\base.py", line 131, in __init__
    super(POSTagger, self).__init__(lang=lang)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\tag\base.py", line 40, in __init__
    self.predictor = self._load_network()

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\tag\base.py", line 137, in _load_network
    self.embeddings = load_embeddings(self.lang, type='cw')

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\load.py", line 61, in load_embeddings
    p = locate_resource(src_dir, lang)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\load.py", line 43, in locate_resource
    if downloader.status(package_id) != downloader.INSTALLED:

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\downloader.py", line 737, in status
    info = self._info_or_id(info_or_id)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\downloader.py", line 507, in _info_or_id
    return self.info(info_or_id)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\downloader.py", line 929, in info
    self._update_index() # If package is not found, most probably we did not

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\downloader.py", line 843, in _update_index
    P = Package.fromcsobj(p)

  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\downloader.py", line 216, in fromcsobj
    language = subdir.split('/')[1]

IndexError: list index out of range

**Comment by xTomax** [comment]
@pythonabehs Did you tried to download the languages prio to application usage?

**Comment by pushpendrapratap** [comment]
I am using python 2.7 (32 bit) on windows 8 .
executing downloader.download("embeddings2.en") command shows me following error:
--------------------------------------------------------------------------------------------------------
[polyglot_data] Error loading TASK:transliteration2: Package
[polyglot_data]     u'TASK:transliteration2' not found in index
False
--------------------------------------------------------------------------------------------------------

also running command, downloader.list(show_packages=False) shows the following:
--------------------------------------------------------------------------------------------------------------
Using default data directory (C:\Users\Pushpendra\AppData\Roaming\polyglot_data)
=================================================================
 Data server index for <http://polyglot.cs.stonybrook.edu/~polyglot/>
=================================================================
Collections:
  [ ] LANG:ru............. Russian              packages and models
  [ ] TASK:morph2/ru...... morph2/ru

([*] marks installed packages)  
----------------------------------------------------------------------------------------------------------
However it should have shown packages for all diff. languages instead of only "russian".

**Comment by pythonabehs** [comment]
@xTomax 
No I haven't downloaded the language. I'm new to this. Could you please help me  do this

**Comment by alexgarel** [comment]
hi @xTomax http://polyglot.readthedocs.io/en/latest/Download.html
It's kind of good practice in the open source world to first read the manual, then ask.
Wish you success.

**Comment by xTomax** [comment]
@alexgarel I bet you were pointing the manual to @pythonabehs ;)
And yes. You shall read the manual and do things step by step in order to understand where your error is comming from and then ask in the rigth place.
Hope you can bet it ;)

**Comment by pythonabehs** [comment]
Thankyou @xTomax  and @alexgarel 
I tried downloading but gives the following error:

C:\Users\a>polyglot download morph2.en
Traceback (most recent call last):
  File "C:\Users\a\Anaconda3\Scripts\polyglot-
script.py", line 11, in <module>
    load_entry_point('polyglot==16.7.4', 'console_scripts', 'polyglot')()
  File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources\__init__.py", line 561, in load_entry_point
  File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources\__init__.py", line 2649, in load_entry_point
  File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources\__init__.py", line 2303, in load
  File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources\__init__.py", line 2309, in resolve
  File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot\__main__.py", line 9, in <module>
    from signal import signal, SIGPIPE, SIG_DFL
ImportError: cannot import name 'SIGPIPE'

**Comment by alexgarel** [comment]
This seems like a bug of polyglot on windows.

Could you please report this problem as a new issue.

A quick local fix is to edit this file and remove all ref to SIGPIPE (won't affect the behaviour of polyglot).

**Comment by alexgarel** [comment]
hum also precise the windows version you are using.

**Comment by pythonabehs** [comment]
Thanks @alexgarel 
removed all ref to SIGPIPE
now it works!!!
