### ISSUE TITLE
Pip install issue on OsX with python 2.7.8

### ISSUE THREAD

**Issue by macarthy** [aboSamoor/polyglot#134]
± pip install polyglot
Collecting polyglot
/Users/macarthy/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Users/macarthy/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading polyglot-16.7.4.tar.gz (126kB)
    100% |████████████████████████████████| 133kB 650kB/s
Requirement already satisfied: futures>=2.1.6 in /Users/macarthy/.pyenv/versions/2.7.8/lib/python2.7/site-packages (from polyglot)
Collecting PyICU>=1.8 (from polyglot)
  Downloading PyICU-1.9.8.tar.gz (183kB)
    100% |████████████████████████████████| 184kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3l/bnbtkwsj23ncm0scfm1dwbwh0000gn/T/pip-build-62PCfi/PyICU/setup.py", line 33, in <module>
        ''')
    RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3l/bnbtkwsj23ncm0scfm1dwbwh0000gn/T/pip-build-62PCfi/PyICU/

Python version is 
± python --version
Python 2.7.8

OsX version 10.11.6

**Comment by vnhnhm** [comment]
```bash
$ brew install icu4c
$ brew link icu4c --force
```

Might help.
