### ISSUE TITLE
No module named 'icu'

### ISSUE THREAD

**Issue by mihirpatel7** [aboSamoor/polyglot#152]
Traceback (most recent call last):
  File "D:/Sentiment/sentiment/SentimentDemo.py", line 2, in <module>
    from polyglot.text import Text,Word
  File "C:\Python36\lib\site-packages\polyglot-16.7.4-py3.6.egg\polyglot\text.py", line 11, in <module>
    from polyglot.detect import Detector, Language
  File "C:\Python36\lib\site-packages\polyglot-16.7.4-py3.6.egg\polyglot\detect\__init__.py", line 1, in <module>
    from .base import Detector, Language
  File "C:\Python36\lib\site-packages\polyglot-16.7.4-py3.6.egg\polyglot\detect\base.py", line 11, in <module>
    from icu import Locale
ModuleNotFoundError: No module named 'icu'

**Comment by Huijun-Cui** [comment]
@janissl  I also met this problem , but my system is Ubuntu , what should I do ?

**Comment by akornilo** [comment]
I just figured out the Unix solution:
Download this file https://pypi.org/project/PyICU/#files, untar, then run `python setup.py install`

**Comment by MiguelNiblock** [comment]
Im having the same issue, even after i installed ibicu-dev with 
`sudo apt-get install libicu-dev`

**Comment by MiguelNiblock** [comment]
> I just figured out the Unix solution:
> Download this file https://pypi.org/project/PyICU/#files, untar, then run `python setup.py install`

I tried that on linux mint and I got the error:
```
Command "/home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dtuxb1cb/PyICU/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0me1_n3v/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-dtuxb1cb/PyICU/
```

**Comment by MiguelNiblock** [comment]
Then when running `pip install PyICU` it also fails.

**Comment by MiguelNiblock** [comment]
It was all solved after I did the following:

`sudo apt-get install build-essential`

Then the following two could be installed successfully:

`pip install PyICU`
and
`pip install pycld2`

Then I could finally run polyglot.

**Comment by grofte** [comment]
Ubuntu

```
pip install polyglot
pip install pyicu
pip install pycld2
pip install morfessor
```

Is there any reason you can't set up the PyPI repository so that those are dependencies? Or at the very least write it in the installation section of your manual?

**Comment by mdjadu** [comment]
polyglot for windows 10
How to install it 
using python3.8
or using conda environment
