### ISSUE TITLE
ImportError: libicule.so.57: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by guigarfr** [aboSamoor/polyglot#153]
I got this error after upgrading to ubuntu 18.04

```
Error
Traceback (most recent call last):
  File "/home/---/.virtualenvs/mltools/lib/python3.6/site-packages/rpscience/tokenizer/listing_titles.py", line 13, in <module>
    from polyglot.detect import Detector
  File "/home/---/.virtualenvs/mltools/lib/python3.6/site-packages/polyglot/detect/__init__.py", line 1, in <module>
    from .base import Detector, Language
  File "/home/---/.virtualenvs/mltools/lib/python3.6/site-packages/polyglot/detect/base.py", line 11, in <module>
    from icu import Locale
  File "/home/---/.virtualenvs/mltools/lib/python3.6/site-packages/icu/__init__.py", line 37, in <module>
    from _icu import *
ImportError: libicule.so.57: cannot open shared object file: No such file or directory
```

**Comment by fnielsen** [comment]
I get this error too. In my Ubuntu 18.04 I have a libicule.so.55.1 in a "snap" directory.

**Comment by fnielsen** [comment]
The following help for Python2 and Python3:

    sudo pip2 install --upgrade  PyICU

    sudo pip3 install --upgrade  PyICU
