### ISSUE TITLE
Named Entity Extraction does not seem to work

### ISSUE THREAD

**Issue by valeriocos** [aboSamoor/polyglot#16]
I would like to use the Named Entity Extraction of Polyglot, so I'm following the documentation at  ``` http://polyglot.readthedocs.org/en/latest/NamedEntityRecognition.html```, however when I execute 
```
print(downloader.supported_languages_table("ner2", 3)) 
``` 
I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/text_analyzer_polyglot.py", line 22, in <module>
    main()
  File "C:/Users/text_analyzer_polyglot.py", line 18, in main
    print(downloader.supported_languages_table("ner2", 3))
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 963, in supported_languages_table
    languages = self.supported_languages(task)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 955, in supported_languages
    collection = self.get_collection(task=task)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 934, in get_collection
    if task: raise TaskNotSupported("Task {} is not supported".format(id))
polyglot.downloader.TaskNotSupported: Task TASK:ner2 is not supported
```

In addition, if I try to execute:
```
blob = """The Israeli Prime Minister Benjamin Netanyahu has warned that Iran poses a "threat to the entire world"."""
    text = Text(blob)
    print (text.entities)
```
I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/text_analyzer_polyglot.py", line 23, in <module>
    main()
  File "C:/Users/text_analyzer_polyglot.py", line 20, in main
    print (text.entities)
  File "C:\Python27\lib\site-packages\polyglot\decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Python27\lib\site-packages\polyglot\text.py", line 124, in entities
    for i, (w, tag) in enumerate(self.ne_chunker.annotate(self.words)):
  File "C:\Python27\lib\site-packages\polyglot\decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Python27\lib\site-packages\polyglot\text.py", line 96, in ne_chunker
    return get_ner_tagger(lang=self.language.code)
  File "C:\Python27\lib\site-packages\polyglot\decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "C:\Python27\lib\site-packages\polyglot\tag\base.py", line 152, in get_ner_tagger
    return NEChunker(lang=lang)
  File "C:\Python27\lib\site-packages\polyglot\tag\base.py", line 99, in __init__
    super(NEChunker, self).__init__(lang=lang)
  File "C:\Python27\lib\site-packages\polyglot\tag\base.py", line 40, in __init__
    self.predictor = self._load_network()
  File "C:\Python27\lib\site-packages\polyglot\tag\base.py", line 104, in _load_network
    self.embeddings = load_embeddings(self.lang, type='cw')
  File "C:\Python27\lib\site-packages\polyglot\decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "C:\Python27\lib\site-packages\polyglot\load.py", line 64, in load_embeddings
    p = locate_resource(src_dir, lang)
  File "C:\Python27\lib\site-packages\polyglot\load.py", line 47, in locate_resource
    if downloader.status(package_id) != downloader.INSTALLED:
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 730, in status
    info = self._info_or_id(info_or_id)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 500, in _info_or_id
    return self.info(info_or_id)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 918, in info
    raise ValueError('Package %r not found in index' % id)
ValueError: Package u'embeddings2.en' not found in index
```

Am I missing something in the documentation?
Could you tell me how to successfully run the Named Entity Extraction?

**Comment by aboSamoor** [comment]
Most probably this is a windows issue. If you want to run it on windows, you need to debug the code and fix it accordingly. I never tested it on windows. You are welcome to submit pull requests to port polyglot to  windows.

To test my hypothesis, try to run polyglot in ubuntu.

**Comment by valeriocos** [comment]
ok, thanks for the pointer. I'll try to spend some time on it

**Comment by stefantcristian** [comment]
It is definitely not a windows error. @aboSamoor You're getting a lot of this crap in debian. Couldn't solve it yet, so please do if you've got any clue :)

**Comment by aboSamoor** [comment]
Hi Stefan,

If you find a solution, please share it with us.

**Comment by silveto** [comment]
For me I have to manually download language models. But it was Windows error too, so this worked: 

In polyglot-16.7.4-py3.5.egg\polyglot\__main__.py__main__.py
Comment lines with SIGPIPE
#from signal import signal, SIGPIPE, SIG_DFL
#signal(SIGPIPE, SIG_DFL)

In polyglot-16.7.4-py3.5.egg\polyglot\downloader.py
Find method:
def fromcsobj(csobj)
and change path.sep to "/"


Then this works on Windows 10 / Python 3.5:
polyglot download LANG:pt

**Comment by kusumlata123** [comment]
I am getting this error on ubantu
for entity in sent.entities:
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/text.py", line 132, in entities
    for i, (w, tag) in enumerate(self.ne_chunker.annotate(self.words)):
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/decorators.py", line 20, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/text.py", line 100, in ne_chunker
    return get_ner_tagger(lang=self.language.code)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/tag/base.py", line 191, in get_ner_tagger
    return NEChunker(lang=lang)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/tag/base.py", line 104, in __init__
    super(NEChunker, self).__init__(lang=lang)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/tag/base.py", line 40, in __init__
    self.predictor = self._load_network()
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/tag/base.py", line 109, in _load_network
    self.embeddings = load_embeddings(self.lang, type='cw', normalize=True)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/load.py", line 61, in load_embeddings
    p = locate_resource(src_dir, lang)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/load.py", line 43, in locate_resource
    if downloader.status(package_id) != downloader.INSTALLED:
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/downloader.py", line 737, in status
    info = self._info_or_id(info_or_id)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/downloader.py", line 507, in _info_or_id
    return self.info(info_or_id)
  File "/home/kusum/anaconda3/envs/coref/lib/python3.7/site-packages/polyglot/downloader.py", line 933, in info
    raise ValueError('Package %r not found in index' % id)
ValueError: Package 'embeddings2.bh' not found in index
