### ISSUE TITLE
polyglot download failing 

### ISSUE THREAD

**Issue by HariMahesh123** [aboSamoor/polyglot#160]
Everything seems to be going Ok then when polyglot tries to load embeddings, ner2 and pos2, it fails. 
Can you/someone please help. 
This is the command the I use to download these packages - 
$HOME/anaconda3/envs/py36/bin/polyglot download embeddings2.en ner2.en pos2.en
Thanks

$HOME/anaconda3/envs/py36/bin/polyglot download embeddings2.en ner2.en pos2.en
Traceback (most recent call last):
  File "/home/travis/anaconda3/envs/py36/bin/polyglot", line 11, in <module>
    load_entry_point('polyglot', 'console_scripts', 'polyglot')()
  File "/home/travis/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/home/travis/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/travis/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/build/Predicta/predicta-spill/src/polyglot/polyglot/__main__.py", line 16, in <module>
    from icu import Locale
  File "/home/travis/anaconda3/envs/py36/lib/python3.6/site-packages/icu/__init__.py", line 37, in <module>
    from _icu import *
ImportError: /home/travis/anaconda3/envs/py36/lib/libstdc++.so.6: file too short
The command "$HOME/anaconda3/envs/py36/bin/polyglot download embeddings2.en ner2.en pos2.en" failed and exited with 1 during .

**Comment by HariMahesh123** [comment]
I rant it again and now I get a different error - 

    ----------------------------------------
Command "/home/travis/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mgt771bo/PyICU/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-knnhnyy9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-mgt771bo/PyICU/
The command "pip install -e "git+git@github.com:aboSamoor/polyglot.git@1e4a01fb67e35a7cab4eaeef1cbe40acb8ea7701#egg=polyglot"" failed and exited with 1 during .

Thanks
