### ISSUE TITLE
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_icu.so, 2): Symbol not found: 

### ISSUE THREAD

**Issue by loretoparisi** [aboSamoor/polyglot#192]
On macOS I have installed icu4 
```sh
export ICU_VERSION=63.1
export PYICU_INCLUDES=/usr/local/Cellar/icu4c/63.1/include
export PYICU_LFLAGS=-L/usr/local/Cellar/icu4c/63.1/lib
export PYICU_CFLAGS=-std=c++11
pip install pyicu
```
Source: https://gist.github.com/loretoparisi/294b8f536750a18746fc6f43f7859928

but when importing `Transliterator` I get
```
>>> from polyglot.transliteration import Transliterator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/polyglot/transliteration/__init__.py", line 1, in <module>
    from .base import Transliterator
  File "/usr/local/lib/python2.7/site-packages/polyglot/transliteration/base.py", line 12, in <module>
    from ..load import load_transliteration_table
  File "/usr/local/lib/python2.7/site-packages/polyglot/load.py", line 16, in <module>
    from .downloader import downloader
  File "/usr/local/lib/python2.7/site-packages/polyglot/downloader.py", line 91, in <module>
    from polyglot.detect.langids import isoLangs
  File "/usr/local/lib/python2.7/site-packages/polyglot/detect/__init__.py", line 1, in <module>
    from .base import Detector, Language
  File "/usr/local/lib/python2.7/site-packages/polyglot/detect/base.py", line 11, in <module>
    from icu import Locale
  File "/usr/local/lib/python2.7/site-packages/icu/__init__.py", line 37, in <module>
    from _icu import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_icu.so, 2): Symbol not found: __ZN6icu_638ByteSink15GetAppendBufferEiiPciPi
  Referenced from: /usr/local/lib/python2.7/site-packages/_icu.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/_icu.so
>>>
```

**Comment by bsamanvitha** [comment]
I got the same error. This answer worked for me: https://stackoverflow.com/a/50364835/8815371
It occurred because Mac has a built-in ICU library. Linking the actual one fixes the problem.
