### ISSUE TITLE
unable to download models 

### ISSUE THREAD

**Issue by adna9** [aboSamoor/polyglot#204]
im on ubuntu 18.4

unable to download models
following error shows up

PolyGlot 2.0.4 by Fabien Letouzey.
tellusererror POLYGLOT: main(): EngineCommand not set

**Comment by lane-c-wagner** [comment]
im getting a 404:
```
Error loading sentiment2.ru: HTTP Error 404: Not Found
```

**Comment by noalevy** [comment]
> im on ubuntu 18.4
> 
> unable to download models
> following error shows up
> 
> PolyGlot 2.0.4 by Fabien Letouzey.
> tellusererror POLYGLOT: main(): EngineCommand not set

@adna9 I think you're mixing up 2 packages - PolyGlot 2.0.4 is not related to this repository

**Comment by noalevy** [comment]
> im getting a 404:
> 
> ```
> Error loading sentiment2.ru: HTTP Error 404: Not Found
> ```

I'm also getting a 404:

[polyglot_data] Error loading transliteration2.en: HTTP Error 404: Not
[polyglot_data]     Found
Error installing package. Retry? [n/y/e]

On retrying, I get the following error:

Traceback (most recent call last):
  File "[redacted]/venv/bin/polyglot", line 11, in <module>
    load_entry_point('polyglot==16.7.4', 'console_scripts', 'polyglot')()
  File "/[redacted]/venv/lib/python3.6/site-packages/polyglot/__main__.py", line 280, in main
    args.func(args)
  File "/[redacted]/venv/lib/python3.6/site-packages/polyglot/__main__.py", line 110, in download
    halt_on_error=args.halt_on_error)
  File "/[redacted]/venv/lib/python3.6/site-packages/polyglot/downloader.py", line 676, in download
    if not self.download(msg.package.id, download_dir,
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by noalevy** [comment]
The downloader is trying to access polyglot.cs.stonybrook.edu/~polyglot, but there's nothing there. Have the models been moved to a different server?

**Comment by vincenzomanzoni** [comment]
+1, same here.

**Comment by twentytwokhz** [comment]
Is there any other server we can use to download the models? Those are critical for the everyday usage of the library

**Comment by stgunholy** [comment]
+1

**Comment by ogiogi93** [comment]
+1 :(

**Comment by noalevy** [comment]
Looks like they're back on the server!

**Comment by ogiogi93** [comment]
It's working!! thank you (人´∀｀)

**Comment by zjlxgxz** [comment]
Hey, may I know is this issue solved?

**Comment by kuuumo** [comment]
> The downloader is trying to access polyglot.cs.stonybrook.edu/~polyglot, but there's nothing there. Have the models been moved to a different server?

Has this problem happened again?

**Comment by idasilva** [comment]
It's seem that the problem happen again: https://github.com/aboSamoor/polyglot/issues/282...
