### ISSUE TITLE
Icelandic embeddings are broken

### ISSUE THREAD

**Issue by hlynurd** [aboSamoor/polyglot#216]
On "polyglot download embeddings2.is"

I get:

hlynur@hlynur:~$ polyglot download embeddings2.is
[polyglot_data] Error loading embeddings2.is: <urlopen error [Errno
[polyglot_data]     110] Connection timed out>
Error installing package. Retry? [n/y/e]
y
Traceback (most recent call last):
  File "/home/hlynur/.local/bin/polyglot", line 8, in <module>
    sys.exit(main())
  File "/home/hlynur/.local/lib/python3.6/site-packages/polyglot/__main__.py", line 292, in main
    args.func(args)
  File "/home/hlynur/.local/lib/python3.6/site-packages/polyglot/__main__.py", line 116, in download
    halt_on_error=args.halt_on_error)
  File "/home/hlynur/.local/lib/python3.6/site-packages/polyglot/downloader.py", line 676, in download
    if not self.download(msg.package.id, download_dir,
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by kusumlata123** [comment]
I am also getting same error:
polyglot download embeddings2.hi ner2.hi download LANG:hi
[polyglot_data] Error loading embeddings2.hi: <urlopen error [Errno
[polyglot_data]     110] Connection timed out>
Error installing package. Retry? [n/y/e]

**Comment by DGaffney** [comment]
I get this on every attempt to download after being told to download when attempting entity extraction...
