### ISSUE TITLE
polyglot not running in windows.

### ISSUE THREAD

**Issue by hodzanassredin** [aboSamoor/polyglot#32]
pip install -U git+https://github.com/aboSamoor/polyglot.git@master 

In cmd:
```
c:\tmp>polyglot download
raceback (most recent call last):
 File "C:\Python27\Scripts\polyglot-script.py", line 9, in <module>
   load_entry_point('polyglot==15.10.3', 'console_scripts', 'polyglot')()
 File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 552, in load_entry_point
   return get_distribution(dist).load_entry_point(group, name)
 File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2672, in load_entry_point
   return ep.load()
 File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
   return self.resolve()
 File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2351, in resolve
   module = __import__(self.module_name, fromlist=['__name__'], level=0)
 File "C:\Python27\lib\site-packages\polyglot\__main__.py", line 9, in <module>
   from signal import signal, SIGPIPE, SIG_DFL
mportError: cannot import name SIGPIPE
```
In idle:
```
from polyglot.downloader import downloader
downloader.download("embeddings2.en")


Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    downloader.download("embeddings2.en")
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 663, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 533, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 507, in _info_or_id
    return self.info(info_or_id)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 929, in info
    self._update_index() # If package is not found, most probably we did not
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 843, in _update_index
    P = Package.fromcsobj(p)
  File "C:\Python27\lib\site-packages\polyglot\downloader.py", line 216, in fromcsobj
    language = subdir.split(path.sep)[1]
IndexError: list index out of range
```

**Comment by aboSamoor** [comment]
There is no plan to support windows. I tested the software on linux and it
worked fine.
