### ISSUE TITLE
Download seems to depend on numpy

### ISSUE THREAD

**Issue by tgalery** [aboSamoor/polyglot#40]
When installing polyglot from scratch all works fine (icu cdl and morphesor are correctly installed), but when using to download models I get the following error:

```
Traceback (most recent call last):
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/bin/polyglot", line 9, in <module>
    load_entry_point('polyglot==15.10.3', 'console_scripts', 'polyglot')()
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/lib/python2.7/site-packages/polyglot/__main__.py", line 21, in <module>
    from polyglot.load import load_morfessor_model
  File "/home/preceptor/source/ca/wiki_extractor/.wikienv/lib/python2.7/site-packages/polyglot/load.py", line 8, in <module>
    import numpy as np
ImportError: No module named numpy
```

Maybe numpy should be included as a dep too.

**Comment by alantian** [comment]
Thanks for pointing it out --- numpy as been added as a dependency at https://github.com/aboSamoor/polyglot/commit/89855fa024686e14547a660539c7630f84b6561d
