### ISSUE TITLE
Python 3 Embedding Loading is Broken

### ISSUE THREAD

**Issue by belph** [aboSamoor/polyglot#76]
When loading `word2vec` embeddings on Python 3, an exception is thrown.

### Steps to reproduce
Requirements:
- Word Embeddings in `some-embeddings.bin` (issue still arises for non-binary format as well)
- `testing.py` with the following contents:
```
from polyglot.mapping import Embedding
load = lambda v: Embedding.from_word2vec(v, binary=(v.endswith(".bin")))
```

Steps:
```
$ python2 -i testing.py
>>> e = load("some-embeddings.bin")
>>> e["dog"]
array([ <<omitted>> ], dtype=float32)
>>> exit()
$ python3 -i testing.py
>>> e = load("some-embeddings.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testing.py", line 7, in <lambda>
    load = lambda v: Embedding.from_word2vec(v, binary=(v.endswith(".bin")))
  File "/Users/pblair/venv3/lib/python3.5/site-packages/polyglot/mapping/embeddings.py", line 245, in from_word2vec
    words, vectors = Embedding._from_word2vec_binary(fname)
  File "/Users/pblair/venv3/lib/python3.5/site-packages/polyglot/mapping/embeddings.py", line 173, in _from_word2vec_binary
    vocab_size, layer1_size = list(map(int, header.split())) # throws for invalid file format
ValueError: invalid literal for int() with base 10: "b'2335882"
```

**Comment by belph** [comment]
I have submitted a Pull Request which fixes this: #77
