### ISSUE TITLE
Import models manually

### ISSUE THREAD

**Issue by AmirHadifar** [aboSamoor/polyglot#94]
Hi, I want to know is it possible to import embedding/transliteration models manually?

**Comment by pythonabehs** [comment]
I tried downloading but gives the following error:

C:\Users\a>polyglot download morph2.en
 Traceback (most recent call last):
 File "C:\Users\a\Anaconda3\Scripts\polyglot-
 script.py", line 11, in 
 load_entry_point('polyglot==16.7.4', 'console_scripts', 'polyglot')()
 File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources_init_.py", line 561, in load_entry_point
 File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources_init_.py", line 2649, in load_entry_point
 File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources_init_.py", line 2303, in load
 File "C:\Users\a\Anaconda3\lib\site-packages\setuptools-36.0.0-py3.5.egg\pkg_resources_init_.py", line 2309, in resolve
 File "C:\Users\a\Anaconda3\lib\site-packages\polyglot-16.7.4-py3.5.egg\polyglot_main_.py", line 9, in 
 from signal import signal, SIGPIPE, SIG_DFL
 ImportError: cannot import name 'SIGPIPE'

Any help is appreciated. Thanks
