### ISSUE TITLE
Can't run polyglot with conda python 3.4 environment

### ISSUE THREAD

**Issue by bakarov** [aboSamoor/polyglot#97]
I have an issue like [this  #one](https://github.com/aboSamoor/polyglot/issues/78) I've already downgraded conda environment from 3.5 to 3.4, and I still have the same error. Installation of pycld2 didn't helped.

`anaconda3/lib/python3.4/site-packages/_icu.cpython-34m.so: undefined symbol: _ZTIN6icu_5514LEFontInstanceE
`

This error appears on `import polyglot.text`, but `import polyglot` works for me.

Also, polyglot for Python 2.7 _without conda_ works fine.

**Comment by bakarov** [comment]
As I've turned out, after uninstalling conda polyglot works fine, so it's definitely a conflict with conda. Is there a way to fix it without uninstalling conda?

**Comment by IbrahimGashaw** [comment]
I have the same problem. I have tried by uninstalling conda but it is not working  import polyglot.text
/home/ibro/anaconda3/bin/python /home/ibro/anaconda3/lib/python3.5/site-packages/polyglot/tokenize/base.py
Traceback (most recent call last):
  File "/home/ibro/anaconda3/lib/python3.5/site-packages/polyglot/tokenize/base.py", line 6, in <module>
    from icu import Locale, BreakIterator
  File "/home/ibro/anaconda3/lib/python3.5/site-packages/icu.py", line 37, in <module>
    from docs import *
  File "/home/ibro/anaconda3/lib/python3.5/site-packages/docs.py", line 23, in <module>
    from _icu import *
ImportError: /home/ibro/anaconda3/lib/python3.5/site-packages/_icu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_5514LEFontInstanceE

**Comment by mvadood** [comment]
I've got the exact same problem too..

**Comment by alissonmsales** [comment]
Same here too!

**Comment by MaraPL** [comment]
Same here, any ways of getting polygot work with conda?

**Comment by jamesdj** [comment]
Same here. Seems like a couple of other issues are duplicates.

**Comment by alexgarel** [comment]
I would advise opening a ticket on the conda project, as they are the one packaging polyglot, it's their responsibility.
